#SPECS INPUT
user = input("enter username")
sysname = input("enter system name")
os = input("enter os name")
model = input("enter model name")
kernel = input("enter kernel name")
uptime = input("enter uptime")
packages = input("enter number of packages")
shell = input("enter shell name")
resolution = input("enter resolution")
de = input("enter desktop environment")
wm = input("enter window manager")
theme = input("enter theme name")
icons = input("enter icons name")
terminal = input("enter terminal name")
cpu = input("enter cpu name")
gpu = input("enter gpu name")
ram = input("enter ram size")
#ACTUAL DREAMFETCH
print(user + "@" + sysname)
print("OS: " + os)
print("Model: " + model)    
print("Kernel: " + kernel)
print("Uptime: " + uptime)
print("Packages: " + packages)
print("Shell: " + shell)
print("Resolution: " + resolution)
print("DE: " + de)
print("WM: " + wm)
print("Theme: " + theme)
print("Icons: " + icons)
print("Terminal: " + terminal)
print("CPU: " + cpu)
print("GPU: " + gpu)
print("Memory: " + ram)
