usercode = input("Enter a code")
code = "KABOOMRICO"
while usercode != code:
    print("Wrong code")
    usercode = input("Enter a code")
if usercode == code:
    print(r"                               ________________")
    print(r"                          ____/ (  (    )   )  \\___")
    print(r"                         /( (  (  )   _    ))  )   )\\")
    print(r"                       ((     (   )(    )  )   (   )  )")
    print(r"                     ((/  ( _(   )   (   _) ) (  () )  )")
    print(r"                    ( (  ( (_)   ((    (   )  .((_ ) .  )_")
    print(r"                   ( (  )    (      (  )    )   ) . ) (   )")
    print(r"                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )")
    print(r"                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )")
    print(r"                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )")
    print(r"                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )")
    print(r"                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )")
    print(r"                  ((  (   )(    (     _    )   _) _(_ (  (_ )")
    print(r"                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)")
    print(r"                   ((__)        \\||lll|l||///          \_))")
    print(r"                            (   /(/ (  )  ) )\   )")
    print(r"                          (    ( ( ( | | ) ) )\   )")
    print(r"                           (   /(| / ( )) ) ) )) )")
    print(r"                         (     ( ((((_(|)_)))))     )")
    print(r"                          (      ||\(|(|)|/||     )")
    print(r"                        (        |(||(||)||||        )")
    print(r"                          (     //|/l|||)|\\ \     )")
    print(r"                        (/ / //  /|//||||\\  \ \  \ _)")
    print(r"-------------------------------------------------------------------------------")
