userinput1 = input("Hello Anonymous,Enter target number")
if userinput1.isdigit():
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("!DATA FOUND!")
    print("!DATA FOUND!")
    print("!DATA FOUND!")
    print("!DATA FOUND!")
    print("TO ACCESS DATA PAY ME 1 BILLION DOLLARS")
else:
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("HACKING IN PROCESS")
    print("!DATA NOT FOUND!")
    print("!DATA NOT FOUND!")
    print("!DATA NOT FOUND!")
    print("!DATA NOT FOUND!")
    userinput1 = input("Enter new target number")
#this is a joke no real data or hacking is done